name: CloudStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.py"

jobs:
  Derleme:
    runs-on: ubuntu-latest

    steps:
      - name: Kaynak Kodunu Al
        uses: actions/checkout@v4
        with:
          path: src

      - name: Build Branch'ini Al
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Eski DosyalarÄ± Temizle
        run: rm -f builds/*.cs3 builds/plugins.json || true

      - name: Java 17 Kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Android SDK Kur
        uses: android-actions/setup-android@v3

      - name: Eklentileri Derle
        run: |
          cd src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 ../builds || true
          cp build/plugins.json ../builds || true

      - name: Build DosyalarÄ±nÄ± Commit & Pushla
        run: |
          cd builds
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ðŸ”„ Otomatik Derleme - $GITHUB_SHA" || exit 0
          git push
